[package]
name = "arrow_display"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-graphics = "0.8.0"

[dev-dependencies]
embedded-graphics-simulator = "0.5.0"
