name: Rust tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install SDL2 for Ubuntu
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl2-dev
    
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    
    # Cache deps
    - name: Cache Cargo registry and target directories
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        # This key uses a hash of your Cargo.toml files to determine if dependencies have changed
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}

    - name: Check if Rust is correctly set up
      run: cargo --version
  
    - name: Install dependencies
      run: cargo build --verbose

    - name: Running tests
      run: cargo test --verbose
      